package engine

import (
	"bufio"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"

	"pcd-blind-web/internal/config"
)

// Runner manages pcd-blind pipeline execution.
type Runner struct {
	binPath string
	dataDir string
}

// NewRunner creates a Runner.
func NewRunner(binPath, dataDir string) *Runner {
	return &Runner{binPath: binPath, dataDir: dataDir}
}

// RunResult holds the outcome of a pipeline run.
type RunResult struct {
	RunID       string
	Success     bool
	Error       string
	NCandidates int
	NResults    int
}

// Start launches pcd-blind asynchronously. progressFn is called with log lines.
// doneFn is called when the run completes.
func (r *Runner) Start(sourceFile string, params config.Params, progressFn func(string), doneFn func(RunResult)) (string, error) {
	runID := "run_" + time.Now().Format("20060102_150405")
	runDir := filepath.Join(r.dataDir, "output", runID)
	if err := os.MkdirAll(runDir, 0755); err != nil {
		return "", fmt.Errorf("create run dir: %w", err)
	}

	// Write config.toml for this run
	cfgPath := filepath.Join(runDir, "config.toml")
	if err := writeConfigTOML(cfgPath, params); err != nil {
		return "", fmt.Errorf("write config: %w", err)
	}

	// Absolute path to source file
	srcPath := filepath.Join(r.dataDir, "source", sourceFile)

	go func() {
		result := r.execute(runID, srcPath, cfgPath, runDir, progressFn)
		doneFn(result)
	}()

	return runID, nil
}

func (r *Runner) execute(runID, srcPath, cfgPath, runDir string, progressFn func(string)) RunResult {
	ctx := RunResult{RunID: runID}

	// Resolve to absolute paths since we may change Dir
	binAbs, _ := filepath.Abs(r.binPath)
	cfgAbs, _ := filepath.Abs(cfgPath)
	srcAbs, _ := filepath.Abs(srcPath)
	runAbs, _ := filepath.Abs(runDir)

	cmd := exec.Command(binAbs, "-c", cfgAbs, srcAbs, runAbs)

	stdout, _ := cmd.StdoutPipe()
	stderr, _ := cmd.StderrPipe()

	if err := cmd.Start(); err != nil {
		ctx.Error = fmt.Sprintf("start pcd-blind: %v", err)
		return ctx
	}

	// Read both stdout and stderr for progress
	go readLines(stdout, progressFn)
	go readLines(stderr, progressFn)

	if err := cmd.Wait(); err != nil {
		ctx.Error = fmt.Sprintf("pcd-blind failed: %v", err)
		return ctx
	}

	ctx.Success = true

	// Count candidates and results from CSV
	candPath := filepath.Join(runDir, "candidates.csv")
	resPath := filepath.Join(runDir, "results.csv")

	if c, err := countCSVRows(candPath); err == nil {
		ctx.NCandidates = c
	}
	if c, err := countCSVRows(resPath); err == nil {
		ctx.NResults = c
	}

	return ctx
}

func readLines(r io.Reader, fn func(string)) {
	scanner := bufio.NewScanner(r)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line != "" {
			fn(line)
		}
	}
}

func countCSVRows(path string) (int, error) {
	f, err := os.Open(path)
	if err != nil {
		return 0, err
	}
	defer f.Close()
	count := 0
	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		count++
	}
	return count - 1, nil // minus header
}

// writeConfigTOML writes the parameters as a TOML config file.
func writeConfigTOML(path string, p config.Params) error {
	toml := fmt.Sprintf(`# Generated by pcd-blind-web

[detect]
pct = %d
ball_diameter = %.1f

[candidates]
z_start = %.1f
z_step = %.1f
z_end = %.1f
cluster_tolerance = %.2f
min_cluster_size = %d
max_cluster_size = 5000
dedup_xy = 0.3
dedup_z = 0.3

[ground]
cyl_radius = %.1f
box_dz_up = %.1f
box_dz_dn = %.1f
outer_ring_min = %.2f
outer_ring_max = %.2f
ransac_distance = %.2f
ransac_iters = %d
wall_nz_max = %.1f
ground_z_pct = %.2f

[recenter]
max_iters = %d
dxy_threshold = %.2f

[features]
tripod_enabled = %v
tripod_bins = 36
tripod_peak_min_ratio = 1.5
tripod_min_peaks = 3
tripod_angle_tolerance_deg = 20.0
compact_z_window = 0.24
ratio_min = %.1f
compact_min = %.2f
dxy_max_residual = %.2f
ground_fraction_min = %.2f

[scoring]
tripod_weight = %.1f
ratio_weight = %.1f
compact_weight = %.1f
dxy_weight = %.1f
ground_weight = %.1f
dedup_radius = %.1f
dedup_z = %.1f

[output]
save_matches = true
`,
		int(p.Pct),
		p.BallDiameter,
		p.ZStart, p.ZStep, p.ZEnd,
		p.ClusterTol, p.MinClusterSize,
		p.CylRadius, p.BoxDzUp, p.BoxDzDn,
		p.OuterRingMin, p.OuterRingMax, p.RansacDist, p.RansacIters,
		p.WallNzMax, p.GroundZPct,
		p.MaxIters, p.DxyThreshold,
		p.TripodEnabled,
		p.RatioMin, p.CompactMin, p.DxyMax, p.GroundMin,
		p.TripodWeight, p.RatioWeight, p.CompactWeight, p.DxyWeight, p.GroundWeight,
		p.DedupRadius, p.DedupZ,
	)
	return os.WriteFile(path, []byte(toml), 0644)
}
